StoreSystem.Web/Controllers/PurchasesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreSystem.Data;
using StoreSystem.Data.Models;
using StoreSystem.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreSystem.Web.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly IPurchaseService purchaseService;
        private readonly ISupplierService supplierService;
        private readonly IWarehouseService warehouseService;

        public PurchasesController(
            IPurchaseService purchaseService,
            ISupplierService supplierService,
            IWarehouseService warehouseService)
        {
            this.purchaseService = purchaseService;
            this.supplierService = supplierService;
            this.warehouseService = warehouseService;
        }

        // GET: Purchases\
        [HttpGet]
        [Authorize(Roles = ROLES.AdminOrOfficeStaffOrSupplier)]
        public async Task<IActionResult> Index()
        {
            this.ViewData["Title"] = "List of purchases";
            var purchases = await purchaseService.GetAllPurchasesAsync();
            return View(purchases);
        }

        // Post: Purchases
        [HttpPost]
        [Authorize(Roles = ROLES.AdminOrOfficeStaffOrSupplier)]
        public async Task<IActionResult> Index(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                searchString = "";
            }
            searchString = searchString.Trim().ToLower();
            var purchases = await purchaseService.GetAllPurchasesAsync();
            var sss = purchases.Where(p => p.Supplier.Name.ToLower().Contains(searchString));
            return View(sss);
        }

        // GET: Purchases/Details/5
        [Authorize(Roles = ROLES.AdminOrOfficeStaffOrSupplier)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await this.purchaseService.FindPurchaseByIDAsync(id ?? -1);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }

        // GET: Purchases/Create
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Create()
        {
            ViewData["SupplierID"] = new SelectList(await this.supplierService.GetAllSuppliersAsync(), "SupplierID", "Name");
            ViewData["WarehouseID"] = new SelectList(await this.warehouseService.GetAllWarehousesAsync(), "WarehouseID", "Name");
            return View();
        }

        // POST: Purchases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Create([Bind("PurchaseID,PurchaseDate,DeadlineDate,DeliveryDate,SupplierID,WarehouseID")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                await this.purchaseService.CreatePurchaseAsync(
                    purchase.SupplierID,
                    purchase.WarehouseID,
                    purchase.PurchaseDate,
                    purchase.DeliveryDate,
                    purchase.DeadlineDate);
                //_context.Add(purchase);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierID"] = new SelectList(await this.supplierService.GetAllSuppliersAsync(), "SupplierID", "Name", purchase.SupplierID);
            ViewData["WarehouseID"] = new SelectList(await this.warehouseService.GetAllWarehousesAsync(), "WarehouseID", "Name", purchase.WarehouseID);
            return View(purchase);
        }

        // GET: Purchases/Edit/5
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await this.purchaseService.FindPurchaseByIDAsync(id ?? -1);
            if (purchase == null)
            {
                return NotFound();
            }
            ViewData["SupplierID"] = new SelectList(await this.supplierService.GetAllSuppliersAsync(), "SupplierID", "Name", purchase.SupplierID);
            ViewData["WarehouseID"] = new SelectList(await this.warehouseService.GetAllWarehousesAsync(), "WarehouseID", "Name", purchase.WarehouseID);
            return View(purchase);
        }

        // POST: Purchases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Edit(int id, [Bind("PurchaseID,PurchaseDate,DeadlineDate,DeliveryDate,SupplierID,WarehouseID")] Purchase purchase)
        {
            if (id != purchase.PurchaseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await this.purchaseService.UpdatePurchaseAsync(
                    purchase.PurchaseID,
                    purchase.SupplierID,
                    purchase.WarehouseID,
                    purchase.PurchaseDate,
                    purchase.DeliveryDate,
                    purchase.DeadlineDate);
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierID"] = new SelectList(await this.supplierService.GetAllSuppliersAsync(), "SupplierID", "Name", purchase.SupplierID);
            ViewData["WarehouseID"] = new SelectList(await this.warehouseService.GetAllWarehousesAsync(), "WarehouseID", "Name", purchase.WarehouseID);
            return View(purchase);
        }

        // GET: Purchases/Delete/5
        [Authorize(Roles = ROLES.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchase = await this.purchaseService.GetPurchaseByIDAsync(id ?? -1);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.purchaseService.DeletePurchaseAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

StoreSystem.Web/Views/Purchases/Create.cshtml
@model StoreSystem.Data.Models.Purchase

@{
    ViewData["Title"] = "Create";
}

<h1>Create a purchase</h1>

<hr />

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group" id="dtp4">
                    <label asp-for="PurchaseDate" class="control-label"></label>
                    <input asp-for="PurchaseDate" class="form-control" />
                    <span asp-validation-for="PurchaseDate" class="text-danger"></span>
                </div>
                <div class="form-group" id="dtp4">
                    <label asp-for="DeadlineDate" class="control-label"></label>
                    <input asp-for="DeadlineDate" class="form-control" />
                    <span asp-validation-for="DeadlineDate" class="text-danger"></span>
                </div>
                <div class="form-group" id="dtp4">
                    <label asp-for="DeliveryDate" class="control-label"></label>
                    <input asp-for="DeliveryDate" class="form-control" />
                    <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SupplierID" class="control-label"></label>
                    <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="WarehouseID" class="control-label"></label>
                    <select asp-for="WarehouseID" class="form-control" asp-items="ViewBag.WarehouseID"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@{await Html.RenderPartialAsync("_ModalAddressCreator");}


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/ModalAddressCreator.js"></script>
    <script type="text/javascript">
        $('#dtp4').datetimepicker({
            format: 'YYYY-MM-DD'
        });
    </script>
}

StoreSystem.Web/Views/Purchases/Delete.cshtml
@model StoreSystem.Data.Models.Purchase

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete a purchase</h1>

@if (User.IsInRole(ROLES.Admin))
{
    <h3>Are you sure you want to delete this purchase?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PurchaseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PurchaseDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DeadlineDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DeadlineDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DeliveryDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Supplier.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Warehouse)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Warehouse.Name)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="PurchaseID" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
}
<div>
    <h1></h1>
    <a asp-action="Index">Back to List</a>
</div>

StoreSystem.Web/Views/Purchases/Details.cshtml
@model StoreSystem.Data.Models.Purchase

@{
    ViewData["Title"] = "Details";
}

<h1>Purchase's details</h1>

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff) || User.IsInRole(ROLES.Supplier))
{
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PurchaseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PurchaseDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DeadlineDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DeadlineDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DeliveryDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Supplier.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Warehouse)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Warehouse.Name)
            </dd>
        </dl>
    </div>
    <div class="form-group">
        <a asp-action="Edit" asp-route-id="@Model.PurchaseID" class="btn btn-primary">Edit</a>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreSystem.Web/Views/Purchases/Edit.cshtml
@model StoreSystem.Data.Models.Purchase

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit a purchase</h1>

<hr />

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="PurchaseID" />
                <div class="form-group">
                    <label asp-for="PurchaseDate" class="control-label"></label>
                    <input asp-for="PurchaseDate" class="form-control" />
                    <span asp-validation-for="PurchaseDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DeadlineDate" class="control-label"></label>
                    <input asp-for="DeadlineDate" class="form-control" />
                    <span asp-validation-for="DeadlineDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DeliveryDate" class="control-label"></label>
                    <input asp-for="DeliveryDate" class="form-control" />
                    <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SupplierID" class="control-label"></label>
                    <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID"></select>
                    <span asp-validation-for="SupplierID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="WarehouseID" class="control-label"></label>
                    <select asp-for="WarehouseID" class="form-control" asp-items="ViewBag.WarehouseID"></select>
                    <span asp-validation-for="WarehouseID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreSystem.Web/Views/Purchases/Index.cshtml
@model IEnumerable<StoreSystem.Data.Models.Purchase>

@{
    ViewData["Title"] = "Index";
}

<h1>Purchases list</h1>

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff) || User.IsInRole(ROLES.Supplier))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <form asp-controller="Purchases" asp-action="Index">
        <p>
            Supplier name: <input type="text" class="form-control" name="searchString">
            <div>
                <input type="submit" class="btn btn-outline-info" value="Search" />
                <a asp-action="Index"><input type="button" class="btn btn-outline-info" value="Reset" /></a>
            </div>
        </p>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PurchaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeadlineDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeliveryDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Supplier)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchaseDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeadlineDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Supplier.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Warehouse.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.PurchaseID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.PurchaseID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.PurchaseID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div>
    <h1></h1>
    <a asp-controller="Home" asp-action="Index">Go to Home</a>
</div>