StoreSystem.Web/Controllers/SalesController.cs
using DinkToPdf;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using StoreSystem.Data;
using StoreSystem.Data.Models;
using StoreSystem.Services;
using StoreSystem.Web.Controllers.Utils;
using StoreSystem.Web.Mappers;
using StoreSystem.Web.Models.ClientViewModels;
using StoreSystem.Web.Models.ProductViewModels;
using StoreSystem.Web.Models.SaleViewModels;
using StoreSystem.Web.Utils;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace StoreSystem.Web.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISaleService saleService;
        private readonly IClientService clientService;
        private readonly IAddressService addressService;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;
        private readonly UserManager<StoreUser> userManager;
        private readonly IViewModelMapper<Sale, SaleInfoViewModel> saleInfoMapper;
        private readonly IViewModelMapper<Sale, SaleCUViewModel> saleCUMapper;
        private readonly IViewModelMapper<ProductSale, ProductLineInfoViewModel> productSaleInfoMapper;
        private readonly IViewModelMapper<Client, ClientInfoViewModel> clientInfoMapper;

        public SalesController(
            ISaleService saleService,
            IClientService clientService,
            IAddressService addressService,
            ICityService cityService,
            ICountryService countryService,
            UserManager<StoreUser> userManager,
            IViewModelMapper<Sale, SaleInfoViewModel> saleInfoMapper,
            IViewModelMapper<Sale, SaleCUViewModel> saleCUMapper,
            IViewModelMapper<ProductSale, ProductLineInfoViewModel> productSaleInfoMapper,
            IViewModelMapper<Client, ClientInfoViewModel> clientInfoMapper)
        {
            this.saleService = saleService ?? throw new ArgumentNullException(nameof(saleService));
            this.clientService = clientService ?? throw new ArgumentNullException(nameof(clientService));
            this.addressService = addressService ?? throw new ArgumentNullException(nameof(addressService));
            this.cityService = cityService ?? throw new ArgumentNullException(nameof(cityService));
            this.countryService = countryService ?? throw new ArgumentNullException(nameof(countryService));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            this.saleInfoMapper = saleInfoMapper ?? throw new ArgumentNullException(nameof(saleInfoMapper));
            this.saleCUMapper = saleCUMapper ?? throw new ArgumentNullException(nameof(saleCUMapper));
            this.productSaleInfoMapper = productSaleInfoMapper ?? throw new ArgumentNullException(nameof(productSaleInfoMapper));
            this.clientInfoMapper = clientInfoMapper ?? throw new ArgumentNullException(nameof(clientInfoMapper));
        }

        private bool CanEdit()
        {
            var canEdit = false;

            if (this.User.IsInRole(ROLES.Admin) || this.User.IsInRole(ROLES.OfficeStaff))
            {
                canEdit = true;
            }
            else
            {
                canEdit = false;
            }
            return canEdit;
        }

        // GET: Sales
        [AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin, ROLES.Client)]
        public async Task<IActionResult> Index()
        {
            int? clientId = null;
            if (this.User.IsInRole(ROLES.Client))
            {
                clientId = (await this.userManager.GetUserAsync(this.User))?.ClientId;
                if (clientId == null)
                {
                    return this.NotFound();
                }
            }
            var sales = await this.saleService.GetSalesWithTotalAsync(clientID: clientId);
            var notClosed = await this.saleService.GetNotClosedSalesAsync();
            return this.View(new SaleIndexViewModel() { SalesList = sales, NotClosedSales = notClosed, CanEdit = this.CanEdit() });
        }

        // GET: Sales/Details/5
        [AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin,ROLES.Client)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.saleService.GetSaleInfoAsync(id);
            if (sale == null)
            {
                return this.NotFound();
            }

            var productsInSale = await this.saleService.GetAllProductsInSaleAsync((int)id);
            var psViewModel = productsInSale.Select(this.productSaleInfoMapper.MapFrom);

            var detailViewModel = new SaleIDetailsViewModel()
            {
                ProductsInSale = psViewModel.ToList(),
                SaleInfo = this.saleInfoMapper.MapFrom(sale),
                CanEdit = this.CanEdit()
            };

            return this.View(detailViewModel);
        }

        //[AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin, ROLES.Client)]
        public async Task<IActionResult> Invoice(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.saleService.GetSaleInfoAsync(id);
            if (sale == null)
            {
                return this.NotFound();
            }

            var productsInSale = await this.saleService.GetAllProductsInSaleAsync((int)id);

            var client = await this.clientService.FindClientWithAddressAsync(sale.ClientID);

            var invoiceViewModel = new InvoiceViewModel()
            {
                ProductsInSale = productsInSale.Select(this.productSaleInfoMapper.MapFrom).ToList(),
                SaleInfo = this.saleInfoMapper.MapFrom(sale),
                ClientInfo = this.clientInfoMapper.MapFrom(client)
            };

            return this.View(invoiceViewModel);
        }

        // GET: Sales/Create
        [AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin)]
        public async Task<IActionResult> Create()
        {
            this.ViewData["Addresses"] = new SelectList(await this.addressService.GetAllAddressesAsync(), "AddressID", "Name");
            this.ViewData["Cities"] = new SelectList(await this.cityService.GetAllCitiesAsync(), "CityID", "Name");
            this.ViewData["Countries"] = new SelectList(await this.countryService.GetAllCountriesAsync(), "CountryID", "Name");
            this.ViewData["Clients"] = new SelectList(await this.clientService.GetAllClientsAsync(), "ClientID", "Name");
            return this.View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SaleCUViewModel sale)
        {
            if (this.ModelState.IsValid)
            {
                await this.saleService.CreateSaleAsync(sale.ClientID, sale.ProductDiscount, sale.DeadlineDate, sale.AddressID, sale.CityID, sale.CountryID);
                return this.RedirectToAction(nameof(Index));
            }

            this.ViewData["Clients"] = new SelectList(await this.clientService.GetAllClientsAsync(), "ClientID", "Name", sale.ClientID);
            this.ViewData["Addresses"] = new SelectList(await this.addressService.GetAllAddressesAsync(), "AddressID", "Name", sale.AddressID);
            this.ViewData["Cities"] = new SelectList(await this.cityService.GetAllCitiesAsync(), "CityID", "Name", sale.CityID);
            this.ViewData["Countries"] = new SelectList(await this.countryService.GetAllCountriesAsync(), "CountryID", "Name", sale.CountryID);

            return this.View(sale);
        }

        // GET: Sales/Edit/5
        [AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var sale = await this.saleService.GetSaleInfoAsync(id);
            if (sale == null)
            {
                return this.NotFound();
            }

            this.ViewData["Clients"] = new SelectList(await this.clientService.GetAllClientsAsync(), "ClientID", "Name", sale.ClientID);
            this.ViewData["Addresses"] = new SelectList(await this.addressService.GetAllAddressesAsync(), "AddressID", "Name", sale.AddressID);
            this.ViewData["Cities"] = new SelectList(await this.cityService.GetAllCitiesAsync(), "CityID", "Name", sale.CityID);
            this.ViewData["Countries"] = new SelectList(await this.countryService.GetAllCountriesAsync(), "CountryID", "Name", sale.CountryID);

            return this.View(this.saleCUMapper.MapFrom(sale));
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRolesAttribute(ROLES.OfficeStaff, ROLES.Admin)]
        public async Task<IActionResult> Edit(int id, SaleCUViewModel sale)
        {
            if (id != sale.SaleID)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    await this.saleService.UpdateSaleAsync(
                        sale.SaleID, sale.ClientID, sale.ProductDiscount,
                        sale.OrderDate, (sale.DeadlineDate - sale.OrderDate).Days,
                        sale.DeliveryDate, sale.AddressID, sale.CityID, sale.CountryID);
                }

StoreSystem.Web/Views/Shared/Print.cshtml
@model string;
@{
    ViewData["Title"] = "View";
    Layout = "_PrintLayout";
}

<div id="maincontent">
    @*@{ var myObject = JsonConvert.DeserializeObject<string>(Model);}*@
    @Model
</div>

StoreSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Store System</title>

    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="~/assets/tether/tether.min.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/jquery-ui-1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    @inject SignInManager<StoreUser> SignInManager

    <section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-0">

        <nav class="navbar beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm bg-color transparent rem1">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="menu-logo">
                <div class="navbar-brand">
                    <span class="navbar-logo">
                        <a href="/">
                            <img src="~/images/shop-icon.png" alt="logo" title="" style="height: 3.8rem;">
                        </a>
                    </span>
                    <span class="navbar-caption-wrap">
                        <a class="navbar-caption text-black display-4 rem1" href="/">
                            SMC
                        </a>
                    </span>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                    <li class="nav-item">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a class="nav-link link text-black display-4 rem1" href="/Manage/Index">
                                <span class="mbri-user mbr-iconfont mbr-iconfont-btn"></span>
                                User
                            </a>
                        }
                        else
                        {
                            <a class="nav-link link text-black display-4 rem1" href="/Account/Login">
                                <span class="mbri-user mbr-iconfont mbr-iconfont-btn"></span>
                                User
                            </a>
                        }
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4 rem1" href="/Products">
                            <span class="mbri-shopping-cart mbr-iconfont mbr-iconfont-btn"></span>
                            Products
                        </a>
                    </li>
                    @if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
                    {
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4  rem1" href="/Clients">
                                <span class="mbri-users mbr-iconfont mbr-iconfont-btn"></span>
                                Clients
                            </a>
                        </li>
                    }
                    @if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff) || User.IsInRole(ROLES.Client))
                    {
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4 rem1" href="/Sales">
                                <span class="mbri-cash mbr-iconfont mbr-iconfont-btn"></span>
                                Sales
                            </a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link link text-black display-4 rem1" href="/Offers">
                                <span class="mbri-credit-card mbr-iconfont mbr-iconfont-btn"></span>
                                Offers
                            </a>
                        </li>
                    }
                    @if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff) || User.IsInRole(ROLES.Supplier))
                    {
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4 rem1" href="/Purchases">
                                <span class="mbri-delivery mbr-iconfont mbr-iconfont-btn"></span>
                                Purchases
                            </a>
                        </li>
                    }
                    @if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
                    {
                        <li class="nav-item">
                            <a class="nav-link link text-black display-4 rem1" href="/Suppliers">
                                <span class="mbri-user2 mbr-iconfont mbr-iconfont-btn"></span>
                                Suppliers
                            </a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link link text-black display-4 rem1" href="/Warehouses">
                            <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
                            Warehouses
                        </a>
                    </li>
                </ul>

            </div>
        </nav>
    </section>
    <section class="engine"><a href="">website creation software</a></section><section class="cid-qTkA127IK8 mbr-fullscreen mbr-parallax-background" id="header2-1">

        <div class="mbr-overlay" style="opacity: 0.9; background-color:rgb(228, 228, 228);"></div>
        <div class="container" style="margin-top:3rem; margin-bottom:3rem">





            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
            <a href="#next">
                <i class="mbri-down mbr-iconfont"></i>
            </a>
        </div>
    </section>
    <section class="cid-qTkAaeaxX5" id="footer1-2">


        <div class="container">
            <div class="media-container-row content text-white">
                <div class="col-12 col-md-2">
                    <div class="media-wrap">
                        <a href="/">
                            <img src="~/images/shop-icon.png" alt="logo">
                        </a>
                    </div>
                </div>
                <div class="col-12 col-md-3 mbr-fonts-style display-7">
                    <h5 class="pb-3">
                        Address
                    </h5>
                    <p class="mbr-text">
                        Al. Malinov
                        <br>City, Sofia
                    </p>
                </div>
                <div class="col-12 col-md-3 mbr-fonts-style display-7">
                    <h5 class="pb-3">
                        Contacts
                    </h5>
                    <p class="mbr-text">
                        Email: stanislav.p.dinev@gmail.com
                        <br>Phone: +359 886 430 498
                        <br>Email: v.yoshovski@yahoo.com
                        <br>Phone: +359 878 853 645
                    </p>
                </div>
                <div class="col-12 col-md-4 mbr-fonts-style display-7">

                    <h5 class="pb-3">
                        Links
                    </h5>
                    <p class="mbr-text">
                        <a class="text-primary" href="https://telerikacademy.com">Telerik Academy</a>
                        <partial name="_LoginPartial" />
                    </p>

                </div>

            </div>
            <div class="footer-lower">
                <div class="media-container-row">
                    <div class="col-sm-12">
                        <hr>
                    </div>
                </div>
                <div class="media-container-row mbr-white">
                    <div class="col-sm-6 copyright">
                        <p class="mbr-text mbr-fonts-style display-7">
                            © Copyright 2019 Stanislav Dinev and Vasil Yoshovski
                        </p>
                    </div>
                    <div class="col-md-6">
                        <div class="social-list align-right">
                            <div class="soc-item">
                                <a href="https://twitter.com/" target="_blank">
                                    <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="https://www.facebook.com/" target="_blank">
                                    <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="https://www.youtube.com/" target="_blank">
                                    <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="https://instagram.com/" target="_blank">
                                    <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="https://plus.google.com/" target="_blank">
                                    <span class="socicon-googleplus socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                            <div class="soc-item">
                                <a href="https://www.behance.net/" target="_blank">
                                    <span class="socicon-behance socicon mbr-iconfont mbr-iconfont-social"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="~/assets/popper/popper.min.js"></script>
    <script src="~/assets/tether/tether.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/dropdown/js/script.min.js"></script>
    <script src="~/assets/touchswipe/jquery.touch-swipe.min.js"></script>
    <script src="~/assets/parallax/jarallax.min.js"></script>
    <script src="~/assets/smoothscroll/smooth-scroll.js"></script>
    <script src="~/assets/theme/js/script.js"></script>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<script src="~/jquery-ui-1.12.1/external/jquery/jquery.js"></script>*@
    <script src="~/jquery-ui-1.12.1/jquery-ui.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

StoreSystem.Web/Views/Shared/_ModalAddressCreator.cshtml
<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title" id="titleNewAddressName">Create address</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="form-group">
                    <label for="newAddressName" id="labelNewAddressName">Enter new address:</label>
                    <input type="text" id="newAddressName" class="form-control" />
                </div>
                <input for="newAddressName" type="button" class="btn btn-outline-info btn-sm" value="Create new address" onclick="createFunction('newAddressName');" />
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<input type="hidden" id="routeToAction" value="" />
<input type="hidden" id="selectToAddTo" value="" />

StoreSystem.Web/Views/Shared/_PrintLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Print manager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store System Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><button class="stakmenu"><span>Home</span></button></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index"><button class="stakmenu"><span>Back to sales list</span></button></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="d-print-none" id="headerbuttons">
        <br />
        <button class="btn btn-info full-width d-print-none" onclick="printNow();">Print</button>
        <br />
        <button class="btn btn-info full-width" onclick="savePdf();">Save to pdf</button>
        <br />
        <button class="btn btn-info full-width" onclick="goBack();">Back to sale</button>
    </div>
    <div id="dialog" title="Result">
        <p id="dialogtext">.</p>
    </div>
    <footer class="border-top footer text-muted d-print-none">
        <div class="container">
            &copy; 2019 - Store management Center - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/jquery-ui-1.12.1/jquery-ui.min.js"></script>

    <script>
        function printNow() {
            window.print();
        }
        function goBack() {
            window.history.back();
        }

        function savePdf() {
            var htmlContent = window.location.href;


            var modelg = {
                Source: htmlContent
            };
            alert("Succefully saved pdf file!");
            $.ajax({
                method: 'post',
                url: "/PdfFromURL",
                data: JSON.stringify(modelg),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    $("#dialog").dialog("open");
                    $("#dialogtext").text(data.text);
                }
            });
        }
        $(function () {
            $("#dialog").dialog(
                { autoOpen: false },
                { modal: true },
                { show: { effect: "scale", duration: 300 } }

            )
        });
    </script>


    @RenderSection("Scripts", required: false)
</body>
</html>