StoreSystem.Web/Models/StoreUserViewModels/StoreUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StoreSystem.Web.Models.StoreUserViewModels
{
    public class StoreUserViewModel
    {
        [Required]
        [MinLength(1)]
        public string UserID { get; set; }

        [Required]
        [MinLength(1)]
        public string UserName;

        [Required]
        [MinLength(5)]
        public string Email { get; set; }

        [Required]
        public string Role { get; set; }

        [Required]
        public bool IsProtected;

        public string Phone { get; set; }
    }
}

StoreSystem.Web/Areas/Admin/Controllers/StoreUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Data;
using StoreSystem.Data.DbContext;
using StoreSystem.Data.Models;
using StoreSystem.Services;
using StoreSystem.Services.Contracts;
using StoreSystem.Web.Constants;
using StoreSystem.Web.Mappers;
using StoreSystem.Web.Models.StoreUserViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreSystem.Web.Controllers
{
    [Area("Admin")]
    public class StoreUsersController : Controller
    {
        private readonly UserManager<StoreUser> userManager;
        private readonly IStoreUserService storeUserService;
        private readonly IDatabaseService databaseService;
        private readonly IManageService manageService;
        private readonly IViewModelMapper<StoreUser, StoreUserViewModel> storeUserMapper;
        private readonly IViewModelMapper<List<StoreUser>, StoreUsersCollectionViewModel> storeUsersCollectionMapper;

        public StoreUsersController(
            UserManager<StoreUser> userManager,
            IStoreUserService storeUserService,
            IDatabaseService databaseService,
            IManageService manageService,
            IViewModelMapper<StoreUser, StoreUserViewModel> storeUserMapper,
            IViewModelMapper<List<StoreUser>, StoreUsersCollectionViewModel> storeUsersCollectionMapper)
        {
            this.userManager = userManager;
            this.storeUserService = storeUserService;
            this.databaseService = databaseService;
            this.manageService = manageService;
            this.storeUserMapper = storeUserMapper;
            this.storeUsersCollectionMapper = storeUsersCollectionMapper;
        }

        // GET: StoreServices
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> UsersGroupedByRole()
        {
            var userRoles = await this.manageService.GetAllRolesAsync();
            return View(userRoles);
        }

        // GET: Users
        [HttpGet]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Index()
        {
            var usersList = await this.manageService.GetAllUsersAsync();

            var clientsList = await this.databaseService.GetUsersNameAndIDByRoleAsync(ROLES.Client);
            var clientsNameList = clientsList.Select(x => x.userName).ToList();
            usersList = usersList.Where(u => clientsNameList.All(cn => cn != u.UserName)).ToList();

            var supplierList = await this.databaseService.GetUsersNameAndIDByRoleAsync(ROLES.Supplier);
            var suppliersNameList = supplierList.Select(x => x.userName).ToList();
            usersList = usersList.Where(u => suppliersNameList.All(cn => cn != u.UserName)).ToList();

            //var mappedList23 = usersList.Select(d => this.storeUserMapper.MapFrom(d)).ToList();
            var mappedList = this.storeUsersCollectionMapper.MapFrom(usersList).StoreUsers.ToList();
            for (int i = 0; i < mappedList.Count; i++)
            {
                var ffff = usersList.Where(u => u.Id == mappedList[i].UserID).FirstOrDefault();
                mappedList[i].Role = (await this.userManager.GetRolesAsync(ffff)).FirstOrDefault();
            }
            return View(mappedList);
        }

        // Post: Users
        [HttpPost]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Index(string searchString)
        {
            var usersList = await this.manageService.GetAllUsersByFilterAsync(0, int.MaxValue, searchString);

            var clientsList = await this.databaseService.GetUsersNameAndIDByRoleAsync(ROLES.Client);
            var clientsNameList = clientsList.Select(x => x.userName).ToList();
            usersList = usersList.Where(u => clientsNameList.All(cn => cn != u.UserName)).ToList();

            var supplierList = await this.databaseService.GetUsersNameAndIDByRoleAsync(ROLES.Supplier);
            var suppliersNameList = supplierList.Select(x => x.userName).ToList();
            usersList = usersList.Where(u => suppliersNameList.All(cn => cn != u.UserName)).ToList();

            //var mappedList23 = usersList.Select(d => this.storeUserMapper.MapFrom(d)).ToList();
            var mappedList = this.storeUsersCollectionMapper.MapFrom(usersList).StoreUsers.ToList();
            for (int i = 0; i < mappedList.Count; i++)
            {
                var ffff = usersList.Where(u => u.Id == mappedList[i].UserID).FirstOrDefault();
                mappedList[i].Role = (await this.userManager.GetRolesAsync(ffff)).FirstOrDefault();
            }
            return View(mappedList);
        }

        //// GET: StoreUsers/SetDefaultPassword
        //[Authorize(Roles = ROLES.Admin)]
        //public async Task<ActionResult> SetDefaultPassword(string userID, string newPasswodString)
        //{
        //    return RedirectToAction("Index");
        //}

        // GET: StoreUsers/ChangeUserRoleToVisitor
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> ChangeUserRoleToVisitor(string id)
        {
            var user = await this.storeUserService.GetUserByName(id);
            if ((user.Email != StoreConstants.ADMIN_EMAIL) && (user.Email != StoreConstants.OFFICE_STAFF_EMAIL))
            {
                await this.databaseService.ChangeUserRoleAsync(user.Id, ROLES.Visitor);
            }
            return RedirectToAction("Index");
        }

        // GET: StoreUsers/ChangeUserRoleToOfficeStaff
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> ChangeUserRoleToOfficeStaff(string id)
        {
            var user = await this.storeUserService.GetUserByName(id);
            if ((user.Email != StoreConstants.ADMIN_EMAIL) && (user.Email != StoreConstants.OFFICE_STAFF_EMAIL))
            {
                await this.databaseService.ChangeUserRoleAsync(user.Id, ROLES.OfficeStaff);
            }
            return RedirectToAction("Index");
        }

        // GET: StoreUsers/ChangeUserRoleToAdmin
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> ChangeUserRoleToAdmin(string id)
        {
            var user = await this.storeUserService.GetUserByName(id);
            if ((user.Email != StoreConstants.ADMIN_EMAIL) && (user.Email != StoreConstants.OFFICE_STAFF_EMAIL))
            {
                await this.databaseService.ChangeUserRoleAsync(user.Id, ROLES.Admin);
            }
            return RedirectToAction("Index");
        }

        // GET: StoreUsers/Configure/5
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> Configure(string id)
        {
            var user = await this.storeUserService.GetUserByName(id);
            var userModel = this.storeUserMapper.MapFrom(user);
            userModel.Role = (await this.userManager.GetRolesAsync(user)).FirstOrDefault();
            if ((userModel.Email != StoreConstants.ADMIN_EMAIL) && (userModel.Email != StoreConstants.OFFICE_STAFF_EMAIL))
            {
                userModel.IsProtected = false;
            }
            else
            {
                userModel.IsProtected = true;
            }
            return View(userModel);
        }

        // GET: StoreUsers/Delete/5
        [HttpGet]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await this.storeUserService.GetUserByName(id);
            var userModel = this.storeUserMapper.MapFrom(user);
            userModel.Role = (await this.userManager.GetRolesAsync(user)).FirstOrDefault();
            if ((userModel.Email != StoreConstants.ADMIN_EMAIL) && (userModel.Email != StoreConstants.OFFICE_STAFF_EMAIL))
            {
                userModel.IsProtected = false;
            }
            else
            {
                userModel.IsProtected = true;
            }
            return View(userModel);
        }

        // POST: StoreUsers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<ActionResult> Delete(string id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var user = await this.storeUserService.GetUserByName(id);
                if ((user.Email != StoreConstants.ADMIN_EMAIL) && (user.Email != StoreConstants.OFFICE_STAFF_EMAIL))
                {
                    var x = await this.userManager.DeleteAsync(user);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Roles
        [HttpGet]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<IActionResult> UserRoles()
        {
            var userRoles = await this.manageService.GetAllRolesAsync();
            return View(userRoles);
        }

        // Post: Roles
        [HttpPost]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<IActionResult> UserRoles(string searchString)
        {
            var userRoles = await this.manageService.GetAllRolesByFilterAsync(0, int.MaxValue, searchString);
            return View(userRoles);
        }
    }
}

StoreSystem.Web/Areas/Admin/Views/StoreUsers/Configure.cshtml
@model StoreUserViewModel

@{
    ViewData["Title"] = "Configure";
}

<h1>Configure user</h1>

@if (User.IsInRole(ROLES.Admin))
{
    <div>
        <hr />
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.UserName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.UserName)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Email)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Role)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Role)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.UserID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.UserID)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Phone)
            </dt>
        </dl>
    </div>
    @if (Model.IsProtected == false)
    {
        <div class="card inline" style="width:240px; height:54px">
            <a class="block btn btn-outline-info" asp-area="Admin" asp-controller="StoreUsers" asp-action="ChangeUserRoleToVisitor" asp-route-id="@Model.UserName" title="Users list">Set to Visitor</a>
        </div>
        <div class="card inline" style="width:240px; height:54px">
            <a class="block btn btn-outline-info" asp-area="Admin" asp-controller="StoreUsers" asp-action="ChangeUserRoleToOfficeStaff" asp-route-id="@Model.UserName" title="Users list">Set to OfficeStaff</a>
        </div>
        <div class="card inline" style="width:240px; height:54px">
            <a class="block btn btn-outline-info" asp-area="Admin" asp-controller="StoreUsers" asp-action="ChangeUserRoleToAdmin" asp-route-id="@Model.UserName" title="Users list">Set to Admin</a>
        </div>

        @*<form asp-area="Admin" asp-controller="StoreUsers" asp-action="SetDefaultPassword">
            <p>
                New password: <input type="text" class="form-control" value="Default@1" name="newPasswodString">
                    <div>
                        <input type="submit" class="btn btn-outline-info" value="Set default password" />
                    </div>
                    <div>
                        <input type="button" class="btn btn-outline-info"  asp-area="Admin" asp-controller="StoreUsers" asp-action="ChangeUserRoleToVisitor" asp-route-id="@Model.UserName" value="Set default password" />
                    </div>
            </p>
            </form>*@
    }
    else
    {
        <h1></h1>
        <h1>
            <font color="red">This user could not be configured!</font>
        </h1>
    }
}
        <div>
            <h1></h1>
            <a asp-action="Index">Back to List</a>
        </div>

StoreSystem.Web/Areas/Admin/Views/StoreUsers/Delete.cshtml
@model StoreUserViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete user</h1>

<h3>Are you sure you want to delete this user?</h3>
<div>
    @if (User.IsInRole(ROLES.Admin))
    {
        <hr />
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.UserName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.UserName)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Email)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Role)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Role)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.UserID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.UserID)
            </dt>
        </dl>
        <dl class="row">
            <dd class="col-sm-2">
                @Html.DisplayNameFor(model => Model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayFor(model => Model.Phone)
            </dt>
        </dl>

        @if (Model.IsProtected == false)
        {
            <form asp-action="Delete">
                <input type="hidden" asp-for="@Model.UserName" />
                <input type="submit" value="Delete" class="btn btn-danger" />
            </form>
        }
        else
        {
            <h1></h1>
            <h1>
                <font color="red">This user could not be deleted!</font>
            </h1>
        }
    }
    <div>
        <h1></h1>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

StoreSystem.Web/Areas/Admin/Views/StoreUsers/Index.cshtml
@model List<StoreUserViewModel>

@{
    ViewData["Title"] = "UsersList";
}

<h1>Users List</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@

<form asp-controller="StoreUsers" asp-action="Index">
    <p>
        User name: <input type="text" class="form-control" name="searchString">
        <div>
            <input type="submit" class="btn btn-outline-info" value="Search" />
            <a asp-action="UsersList"><input type="button" class="btn btn-outline-info" value="Reset" /></a>
        </div>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <td>
                UserName
            </td>
            <td>
                Email
            </td>
            <td>
                Role
            </td>
            <td></td>
            <td></td>
        </tr>
        @*<tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>*@
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @*<a asp-controller="StoreUsers" asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
            <a asp-controller="StoreUsers" asp-action="Details" asp-route-id="@item.UserName">Details</a> |*@
                <a asp-area="Admin" asp-controller="StoreUsers" asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
            </td>
            <td>
                <a asp-area="Admin" asp-controller="StoreUsers" asp-action="Configure" asp-route-id="@item.UserName">Configure</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<div>
    <a asp-area="Admin" asp-controller="StoreConfigurations" asp-action="Index">Back to StoreConfigurations</a>
</div>

StoreSystem.Web/Areas/Admin/Views/StoreUsers/UserRoles.cshtml
@model List<IdentityRole>

@{
    ViewData["Title"] = "User Roles";
}

<h1>User roles list</h1>

@if (User.IsInRole(ROLES.Admin))
{
    <form asp-controller="StoreUser" asp-action="UserRoles">
        <p>
            User role: <input type="text" class="form-control" name="searchString">
            <div>
                <input type="submit" class="btn btn-outline-info" value="Search" />
                <a asp-action="UserRoles"><input type="button" class="btn btn-outline-info" value="Reset" /></a>
            </div>
        </p>
    </form>

    <table class="table">
        <thead>
            @*<tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th></th>
                </tr>*@
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div>
    <a asp-area="Admin" asp-controller="StoreConfigurations" asp-action="Index">Back to StoreConfigurations</a>
</div>