StoreSystem.Web/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreSystem.Data;
using StoreSystem.Data.Models;
using StoreSystem.Services;
using System;
using System.Threading.Tasks;

namespace StoreSystem.Web.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ICountryService countryService;

        public CountriesController(ICountryService countryService)
        {
            this.countryService = countryService ?? throw new ArgumentNullException(nameof(countryService));
        }

        // GET: Populate Countries From JSON
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> PopulateCountriesFromJSON()
        {
            //var ddd = this.Configuration.GetSection("PathsForInitialDatabaseData").GetValue<bool>("IsEnabled");
            this.ViewData["Title"] = "List of countries";
            var createdCitiesCount = await this.countryService.PopulateCountriesFromJSONAsync(
                "..\\DatabaseInitializationArchiveJSON",
                "CountriesInitial.json");
            return RedirectToAction(nameof(Index));
        }

        // GET: Countries
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Index(string searchString)
        {
            this.ViewData["Title"] = "List of countries";
            var result = searchString == null ?
                await this.countryService.GetAllCountriesAsync() :
                await this.countryService.GetAllCountriesByFilterAsync(0, int.MaxValue, searchString);
            return View(result);
        }

        // GET: Countries/Details/5
        [HttpGet]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryService.FindCountryByIDAsync(id ?? -1);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // GET: Countries/Create
        [HttpGet]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CountryID,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                await this.countryService.CreateCountryAsync(country.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Edit/5
        [HttpGet]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryService.FindCountryByIDAsync(id ?? -1);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = ROLES.AdminOrOfficeStaff)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CountryID,Name")] Country country)
        {
            if (id != country.CountryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await this.countryService.UpdateCountryAsync(country.CountryID, country.Name);
                return RedirectToAction(nameof(Index));
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        [HttpGet]
        [Authorize(Roles = ROLES.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryService.FindCountryByIDAsync(id ?? -1);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = ROLES.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await this.countryService.DeleteCountryAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

StoreSystem.Web/Views/Countries/Create.cshtml
@model StoreSystem.Data.Models.Country

@{
    ViewData["Title"] = "Create";
}

<h1>Create a country</h1>

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreSystem.Web/Views/Countries/Delete.cshtml
@model StoreSystem.Data.Models.Country

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete a country</h1>

@if (User.IsInRole(ROLES.Admin))
{
    <h3>Are you sure you want to delete this country?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="CountryID" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
}
<div>
    <h1></h1>
    <a asp-action="Index">Back to List</a>
</div>

StoreSystem.Web/Views/Countries/Details.cshtml
@model StoreSystem.Data.Models.Country

@{
    ViewData["Title"] = "Details";
}

<h1>Country details</h1>

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>
    <div class="form-group">
        <a asp-action="Edit" asp-route-id="@Model.CountryID" class="btn btn-primary">Edit</a>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreSystem.Web/Views/Countries/Edit.cshtml
@model StoreSystem.Data.Models.Country

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit a country</h1>

<hr />

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="CountryID" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreSystem.Web/Views/Countries/Index.cshtml
@model IEnumerable<StoreSystem.Data.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Countries list</h1>

@if (User.IsInRole(ROLES.Admin) || User.IsInRole(ROLES.OfficeStaff))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <form asp-controller="Countries" asp-action="PopulateCountriesFromJSON">
        <p>
            <div>
                <input type="submit" class="btn btn-outline-info" value="Auto populate from JSON" />
            </div>
        </p>
    </form>

    <form asp-controller="Countries" asp-action="Index">
        <p>
            Country name: <input type="text" class="form-control" name="searchString">
            <div>
                <input type="submit" class="btn btn-outline-info" value="Search" />
                <a asp-action="Index"><input type="button" class="btn btn-outline-info" value="Reset" /></a>
            </div>
        </p>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.CountryID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.CountryID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.CountryID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div>
    <a asp-area="Admin" asp-controller="StoreConfigurations" asp-action="Index">Back to StoreConfigurations</a>
</div>